/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

/**
 *
 * @author kirito205
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrograma1 = new javax.swing.JButton();
        btnPrograma2 = new javax.swing.JButton();
        btnPrograma3 = new javax.swing.JButton();
        btnPrograma4 = new javax.swing.JButton();
        btnPrograma5 = new javax.swing.JButton();
        btnPrograma6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrograma1.setText("Programa 1");
        btnPrograma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrograma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        btnPrograma2.setText("Programa 2");
        btnPrograma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrograma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        btnPrograma3.setText("Programa 3");
        btnPrograma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrograma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnPrograma4.setText("Programa 4");
        btnPrograma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrograma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        btnPrograma5.setText("Programa 5");
        btnPrograma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrograma5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        btnPrograma6.setText("Programa 6");
        btnPrograma6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograma6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrograma6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrograma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma1ActionPerformed
        // TODO add your handling code here:
        Factorial n=new Factorial();
        n.show(true);
    }//GEN-LAST:event_btnPrograma1ActionPerformed

    private void btnPrograma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma2ActionPerformed
        // TODO add your handling code here:
        ParInpar n=new ParInpar();
        n.show(true);
    }//GEN-LAST:event_btnPrograma2ActionPerformed

    private void btnPrograma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma3ActionPerformed
        // TODO add your handling code here:
        Programacion n=new Programacion();
        n.show(true);
    }//GEN-LAST:event_btnPrograma3ActionPerformed

    private void btnPrograma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma4ActionPerformed
        // TODO add your handling code here:
        MutiplicacionOsuma n=new MutiplicacionOsuma();
        n.show(true);
    }//GEN-LAST:event_btnPrograma4ActionPerformed

    private void btnPrograma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma5ActionPerformed
        // TODO add your handling code here:
        CalificacionesRandom n=new CalificacionesRandom();
        n.show(true);
    }//GEN-LAST:event_btnPrograma5ActionPerformed

    private void btnPrograma6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograma6ActionPerformed
        // TODO add your handling code here:
        Binario n=new Binario();
        n.show(true);
    }//GEN-LAST:event_btnPrograma6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrograma1;
    private javax.swing.JButton btnPrograma2;
    private javax.swing.JButton btnPrograma3;
    private javax.swing.JButton btnPrograma4;
    private javax.swing.JButton btnPrograma5;
    private javax.swing.JButton btnPrograma6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
